[package]
name = "shared-clipboard-common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tokio-websockets = { version = "0.11", default-features = false }
